modLoader = "javafml"
loaderVersion = "${neo_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Edivad99/MoreJeiInfo/issues"

[[mods]]
modId = "morejeiinfo"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/Edivad99/MoreJeiInfo"
authors = "Edivad99"
displayTest = "NONE"
description = "Adds more information in tooltips"

[[dependencies.morejeiinfo]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.morejeiinfo]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"