modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Edivad99/MoreJeiInfo/issues"

[[mods]]
  modId = "morejeiinfo"
  version = "${mod_version}"
  displayName = "${mod_name}"
  displayURL = "https://github.com/Edivad99/MoreJeiInfo"
  updateJSONURL = "https://api.modrinth.com/updates/morejeiinfo/forge_updates.json?neoforge=include"
  authors = "${mod_author}"
  displayTest = "NONE"
  description = "${mod_description}"

[[dependencies.morejeiinfo]]
  modId = "neoforge"
  type = "required"
  versionRange = "${neoforge_version_range}"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.morejeiinfo]]
  modId = "minecraft"
  type = "required"
  versionRange = "${minecraft_version_range}"
  ordering = "NONE"
  side = "BOTH"
