name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --max-workers 1

      - name: Clean build/libs folder
        run: rm -f build/libs/*

      - name: Make Changelog
        run: ./gradlew makeChangelog --no-daemon --max-workers 1

      - name: Publish
        run: ./gradlew publishMods --no-daemon --max-workers 1